package com.zenvyra.service;

import com.zenvyra.dto.response.FixSuggestionResponse;
import com.zenvyra.model.Website;
import com.zenvyra.repository.WebsiteRepository;
import com.zenvyra.util.LogSanitizer;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;

import java.util.ArrayList;
import java.util.List;

@Slf4j
@Service
@RequiredArgsConstructor
public class AutoFixService {

    private final OpenAiService openAiService;
    private final WebsiteRepository websiteRepository;

    public FixSuggestionResponse getFixForIssue(String websiteId, String issueType) {
        Website website = websiteRepository.findById(websiteId)
                .orElseThrow(() -> new RuntimeException("Website not found"));

        log.info("Generating fix for issue: {} on {}", issueType, LogSanitizer.url(website.getUrl()));

        return switch (issueType) {
            case "missing_cookie_banner" -> generateCookieBannerFix(website);
            case "missing_privacy_policy" -> generatePrivacyPolicyFix(website);
            case "ssl_invalid" -> generateSSLFix(website);
            case "no_https_redirect" -> generateHttpsRedirectFix(website);
            default -> throw new RuntimeException("No fix implementation for issue type: " + issueType);
        };
    }

    private FixSuggestionResponse generateCookieBannerFix(Website website) {
        String snippet = """
                <!-- Zenvyra Cookie Consent Banner -->
                <div id="compliance-cookie-banner" style="position: fixed; bottom: 0; left: 0; right: 0; background: #1f2937; color: white; padding: 1rem; display: flex; justify-content: space-between; align-items: center; z-index: 9999;">
                    <p style="margin: 0;">We use cookies to improve your experience. By continuing to browse, you agree to our use of cookies.</p>
                    <button onclick="document.getElementById('compliance-cookie-banner').style.display='none'" style="background: #3b82f6; color: white; border: none; padding: 0.5rem 1rem; border-radius: 0.25rem; cursor: pointer;">Accept</button>
                </div>
                """;

        return FixSuggestionResponse.builder()
                .issueType("missing_cookie_banner")
                .title("Cookie Consent Banner")
                .description("Add a simple cookie consent banner to your website.")
                .codeSnippet(snippet)
                .language("html")
                .steps(List.of(
                        "Copy the HTML snippet below.",
                        "Paste it just before the closing </body> tag in your main layout or index.html file.",
                        "Save and deploy your website."
                ))
                .aiExplanation("This snippet provides a basic but effective cookie consent banner. For full GDPR compliance, you might want to categorize cookies and allow granular control.")
                .build();
    }

    private FixSuggestionResponse generatePrivacyPolicyFix(Website website) {
        String companyName = website.getName() != null ? website.getName() : website.getUrl();
        String fullPolicy = openAiService.generatePolicy("Privacy Policy", companyName, "Technology", "English");

        return FixSuggestionResponse.builder()
                .issueType("missing_privacy_policy")
                .title("AI-Generated Privacy Policy")
                .description("A comprehensive, GDPR-compliant privacy policy tailored for your business.")
                .fullContent(fullPolicy)
                .fileName("privacy-policy.html")
                .steps(List.of(
                        "Download the privacy-policy.html file or copy the content.",
                        "Create a new page on your website at /privacy-policy.",
                        "Paste the generated content onto that page.",
                        "Add a link to the Privacy Policy in your website footer."
                ))
                .aiExplanation("This policy was generated by AI based on standard compliance requirements. Please review it to ensure it accurately reflects your data handling practices.")
                .build();
    }

    private FixSuggestionResponse generateSSLFix(Website website) {
        return FixSuggestionResponse.builder()
                .issueType("ssl_invalid")
                .title("SSL Certificate Setup")
                .description("Your website needs a valid SSL certificate for secure communication.")
                .steps(List.of(
                        "If you use Cloudflare, enable 'Full' or 'Full (strict)' SSL mode.",
                        "If you use a VPS, install Let's Encrypt using Certbot: `sudo certbot --nginx -d " + website.getUrl().replaceAll("https?://", "") + "`",
                        "If you use a shared hosting, look for 'SSL/TLS' settings in your cPanel and enable 'AutoSSL'.",
                        "Verify that your URL starts with https:// after installation."
                ))
                .aiExplanation("SSL certificates encrypt the data between your users and your server, which is a fundamental requirement for modern security and SEO.")
                .build();
    }

    private FixSuggestionResponse generateHttpsRedirectFix(Website website) {
        String domain = website.getUrl().replaceAll("https?://", "");
        String snippet = String.format("""
                # Nginx Configuration for HTTP to HTTPS redirect
                server {
                    listen 80;
                    server_name %s;
                    return 301 https://$host$request_uri;
                }
                """, domain);

        return FixSuggestionResponse.builder()
                .issueType("no_https_redirect")
                .title("HTTP to HTTPS Redirect")
                .description("Ensure all traffic is automatically redirected to the secure HTTPS version of your site.")
                .codeSnippet(snippet)
                .language("nginx")
                .steps(List.of(
                        "Open your Nginx configuration file (usually in /etc/nginx/sites-available/).",
                        "Add the server block provided below.",
                        "Test the configuration with `nginx -t`.",
                        "Reload Nginx with `systemctl reload nginx`."
                ))
                .aiExplanation("Redirecting HTTP to HTTPS ensures that users don't accidentally use an unencrypted connection, protecting their data and improving your site's credibility.")
                .build();
    }
}
